language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install: pip install flake8
script: 
  - flake8 eve
  - python setup.py test
services: 
  - mongodb
  - redis-server
before_script:
  - "ulimit -n 1024"
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'
branches:
  only:
    - master
    - develop
